# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-11 09:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0020_old_tree_cleanup'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediumWebsite',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='cmsmedium_mediumwebsite', serialize=False, to='cms.CMSPlugin')),
                ('url', models.URLField(help_text='URL of medium blog website', verbose_name='blog address')),
                ('posts', models.PositiveSmallIntegerField(default=10, verbose_name='Maximum number of posts to display')),
                ('cache', models.DurationField(default=datetime.timedelta(seconds=600), verbose_name='Frequency to which check for new blog posts')),
            ],
            options={
                'verbose_name': 'Medium website',
                'verbose_name_plural': 'Medium websites',
            },
            bases=('cms.cmsplugin',),
        ),
    ]
